vit_guest_book_homepage:
    pattern:  /
    defaults: { _controller: VitGuestBookBundle:Default:index }

vit_guest_book_add_comment:
    pattern:  /create
    defaults: { _controller: VitGuestBookBundle:Default:create }