parameters:
#    vit_guest_book.example.class: Vit\GuestBookBundle\Example

services:
#    vit_guest_book.example:
#        class: %vit_guest_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
